apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: webapp